### ISSUE TITLE
Azure AddonManifest comment refers to Amazon/RDS

### ISSUE THREAD

**Issue by virklba** [Apprenda/Apprenda-Azure#1]
Copy/Paste is a killer.

https://github.com/Apprenda/Apprenda-Azure/blob/a85bc09bde1930f591a39859c7ea6e4da16d732c/Azure%20Storage%20AddIn/AddonManifest.xml#L17

**Comment by dutronlabs** [comment]
Thanks for the extra pair of eyes. :)
